name: Déploiement sur GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload du site
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Déployer le site
        id: deployment
        uses: actions/deploy-pages@v2
